CMD ["/bin/bash", "-c", "ls -la /app && ./forum"]FROM golang:1.20.1-alpine3.16 as base
LABEL Team="msarvaro nmagau" Project="Rabbit" 

RUN apk add build-base 
WORKDIR /app 
COPY . .
RUN go build -o forum ./cmd/app/

FROM alpine:3.16
WORKDIR /app

RUN apk add --no-cache bash

COPY --from=base /app/forum /app/forum

RUN chmod +x /app/forum

EXPOSE 7777

CMD ["/bin/bash", "-c", "./forum"]
