DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS post_likes;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS comment_likes;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS posts_categories;